### ISSUE TITLE
Container not working in docker-compose with swarm

### ISSUE THREAD

**Issue by nbartels** [hypriot/rpi-mysql#11]
Hi there,

I use a 4 node HypriotOS cluster and have a problem running running rpi-mysql as one service in docker-compose-yml.

The error message is: **no suitable node (unsupported platform on 4 nodes)**

According to my understand and checks the architecture cluster is **armv7l**, but the image used is **amd64**. Here is the corresponding output:

docker info:
```shell
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: v8gvd8b8mj691a60zwqamqmsz
 Is Manager: true
 ClusterID: izjv51lqodr8grt7ak1g005pd
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.3.1
 Manager Addresses:
  192.168.3.1:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.34-hypriotos-v7+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 976.7MiB
Name: hydra
ID: 6SGF:7I46:ZZWD:AWN5:TCVS:R37F:CIK7:5JOX:ACPQ:YI5H:IYHN:KIKT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
docker service inspect openhab-suite_mysqldb:

```json
[
    {
        "ID": "soqhiur1f612rsg7hwtf7ukw7",
        "Version": {
            "Index": 2211
        },
        "CreatedAt": "2018-06-16T01:41:43.341077286Z",
        "UpdatedAt": "2018-06-16T01:41:43.348289301Z",
        "Spec": {
            "Name": "openhab-suite_mysqldb",
            "Labels": {
                "com.docker.stack.image": "hypriot/rpi-mysql",
                "com.docker.stack.namespace": "openhab-suite"
            },
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "hypriot/rpi-mysql:latest@sha256:c1567c885cf560da66a647f91f7e16bfeea2968895f859b5732583a8db3570ea",
                    "Labels": {
                        "com.docker.stack.namespace": "openhab-suite"
                    },
                    "Env": [
                        "MYSQL_DATABASE=openhab2",
                        "MYSQL_PASSWORD=ignorethis",
                        "MYSQL_ROOT_PASSWORD=superignorethis",
                        "MYSQL_USER=someuser"
                    ],
                    "Privileges": {
                        "CredentialSpec": null,
                        "SELinuxContext": null
                    },
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/swarm/volumes/mysql/",
                            "Target": "/var/lib/mysql"
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Isolation": "default"
                },
                "Resources": {},
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
                "Networks": [
                    {
                        "Target": "8lkdos19at3susum00dsofsbs",
                        "Aliases": [
                            "mysqldb"
                        ]
                    }
                ],
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 3306,
                        "PublishedPort": 3306,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 3306,
                        "PublishedPort": 3306,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 3306,
                    "PublishedPort": 3306,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "ycxuvpuz55wn8li2g3pz7pvpy",
                    "Addr": "10.255.1.71/16"
                },
                {
                    "NetworkID": "8lkdos19at3susum00dsofsbs",
                    "Addr": "10.0.2.6/24"
                }
            ]
        }
    }
]
```

and last the docker-compose.yml:

```yml
version: '3'

services:
#  openhab:
#    image: "openhab/openhab:2.2.0-armhf-debian"
#    depends_on:
#      - mysqldb
#      - mosquitto
#    restart: always
#    ports:
#      - "80:8080"
#      - "443:8443"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./timezone:/etc/timezone:ro
#      - /swarm/volumes/openhab/config:/openhab/conf
#      - /swarm/volumes/openhab/persist:/openhab/userdata/persistence
#      - /swarm/volumes/openhab/logs:/openhab/userdata/logs
#      - ./backup:/backups
#    networks:
#      - openhab_net
  mysqldb:
   image: hypriot/rpi-mysql
   volumes:
      - /swarm/volumes/mysql/:/var/lib/mysql
   ports:
      - "3306:3306"
   restart: always
   environment:
      MYSQL_ROOT_PASSWORD: "superignorethis"
      MYSQL_DATABASE: openhab2
      MYSQL_USER: someuser
      MYSQL_PASSWORD: "ignorethis"
   networks:
      - openhab_net
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    restart: always
    ports:
       - "1883:1883"
       - "9001:9001"
    volumes:
       - /swarm/volumes/mqtt/config:/mqtt/config:ro
       - /swarm/volumes/mqtt/log:/mqtt/log
       - /swarm/volumes/mqtt/data:/mqtt/data
    networks:
       - openhab_net
networks:
  openhab_net:
```

BTW the mosquitto image works without a problem ...
