### ISSUE TITLE
Problem with entrypoint.sh

### ISSUE THREAD

**Issue by maxisme** [hypriot/rpi-mysql#17]
Whenever

```
  db:
    image: hypriot/rpi-mysql
    ports:
      - "32000:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=foo
      - MYSQL_DATABASE=bar
      - MYSQL_USER=demouser
      - MYSQL_PASSWORD=demopassword
    volumes:
      - ./db/schema:/docker-entrypoint-initdb.d/:ro
```

Inside `/db/schema` I have `1.sql`:
```
USE `bar`;

CREATE TABLE `Logs` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_message` varchar(50) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `message` text COLLATE utf8_bin,
  `read` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);
```

I receive the error:
> ERROR: 1064  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

When I use the `tobi312/rpi-mysql` image everything works as expected. 

Inside the container when runnning:

```
$ cat /tmp/mysql-first-time.sql 
```
I get:
```
DELETE FROM mysql.user ;
CREATE USER 'root'@'%' IDENTIFIED BY 'demopassword' ;
GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
DROP DATABASE IF EXISTS test ;
CREATE DATABASE IF NOT EXISTS `bar` ;
CREATE USER 'demouser'@'%' IDENTIFIED BY 'demopassword' ;
GRANT ALL ON `bar`.* TO 'demouser'@'%' ;
FLUSH PRIVILEGES ;
USE `bar`;

CREATE TABLE `Logs` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_message` varchar(50) CHARACTER SET utf8 NOT NULL DEFAULT '',
  `message` text COLLATE utf8_bin,
  `read` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);
```

Which seems to have no syntax error other than the space?
